---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
market: TSXV
sampling: 100ms
enable_retransmission: false
max_retransmissions: 10000
retransmission_block_size: 20000
host: 233.102.209.235:61002
interface: $local_interface:61002
retransmission_request_address: 142.201.149.36:61020
retransmission_response_address: 142.201.149.36:61050
...
