---
service_locator:
  address: $service_locator_address
  username: market_data_feed
  password: $admin_password

data_store: market_data.db
sampling: 100ms
start_time: 2018-06-18 19:00:00
tickers_path: tickers.yml
client_count: 40
...
