---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
use_broker_number: true
consolidate_mpids: false
market: TSX
sampling: 100ms
enable_retransmission: false
max_retransmissions: 10000
retransmission_block_size: 20000
host: "233.102.209.219:61100"
interface: "$local_interface:61100"
retransmission_request_address: "142.201.149.44:61102"
retransmission_response_address: "142.201.149.44:61103"

mpid_mappings:
  - source: 1
    name: ANON
  - source: 2
    name: RBCC
  - source: 3
    name: TRIS
  - source: 4
    name: VERS
  - source: 5
    name: PFSS
  - source: 6
    name: UNIO
  - source: 7
    name: TDSI
  - source: 8
    name: MASC
  - source: 9
    name: BMON
  - source: 10
    name: FECC
  - source: 11
    name: ORIO
  - source: 12
    name: WWCM
  - source: 13
    name: INST
  - source: 14
    name: ITGC
  - source: 15
    name: UBSC
  - source: 16
    name: PARA
  - source: 17
    name: IWSL
  - source: 18
    name: GCMS
  - source: 19
    name: DESJ
  - source: 20
    name: CRED
  - source: 21
    name: BRCO
  - source: 22
    name: GRAY
  - source: 23
    name: SSGM
  - source: 24
    name: CLAR
  - source: 25
    name: ODLU
  - source: 26
    name: COMM
  - source: 27
    name: DUND
  - source: 28
    name: MCAS
  - source: 29
    name: LGOR
  - source: 30
    name: EMII
  - source: 31
    name: DDSI
  - source: 32
    name: CITC
  - source: 33
    name: CANA
  - source: 34
    name: MAIS
  - source: 35
    name: FRIE
  - source: 36
    name: WDLC
  - source: 37
    name: MMMI
  - source: 38
    name: GCSI
  - source: 39
    name: MLCI
  - source: 40
    name: NORS
  - source: 41
    name: SSCC
  - source: 42
    name: GMCI
  - source: 43
    name: CALD
  - source: 44
    name: JGCL
  - source: 45
    name: LOMC
  - source: 46
    name: BLAC
  - source: 47
    name: THCC
  - source: 48
    name: LAUR
  - source: 50
    name: JCCL
  - source: 51
    name: DBSL
  - source: 52
    name: NBDB
  - source: 53
    name: MSCL
  - source: 54
    name: GLSC
  - source: 55
    name: BNPS
  - source: 56
    name: BURG
  - source: 57
    name: IBCI
  - source: 58
    name: QTRD
  - source: 59
    name: PACI
  - source: 60
    name: MANF
  - source: 62
    name: HAYS
  - source: 63
    name: BYRO
  - source: 64
    name: OCTA
  - source: 65
    name: GSCO
  - source: 66
    name: POPE
  - source: 67
    name: NORT
  - source: 68
    name: LEED
  - source: 69
    name: CITI
  - source: 70
    name: BERK
  - source: 71
    name: BRAN
  - source: 72
    name: CSSC
  - source: 73
    name: SPRO
  - source: 74
    name: GMPS
  - source: 75
    name: MGIS
  - source: 76
    name: IASI
  - source: 77
    name: PETE
  - source: 78
    name: SALM
  - source: 79
    name: CIBC
  - source: 80
    name: NBFI
  - source: 81
    name: HSBC
  - source: 82
    name: WEST
  - source: 83
    name: RESE
  - source: 84
    name: INDE
  - source: 85
    name: SCOT
  - source: 86
    name: PCLP
  - source: 88
    name: ETRD
  - source: 89
    name: RAYJ
  - source: 90
    name: BARC
  - source: 92
    name: POLL
  - source: 93
    name: TOLL
  - source: 94
    name: HAMP
  - source: 95
    name: WOLV
  - source: 97
    name: MPAR
  - source: 99
    name: JITN
  - source: 100
    name: TSXB
  - source: 101
    name: FIMA
  - source: 102
    name: INVE
  - source: 105
    name: LIGH
  - source: 111
    name: FMKL
  - source: 121
    name: JENN
  - source: 123
    name: CITI
  - source: 124
    name: QUES
  - source: 132
    name: ACKE
  - source: 141
    name: BOLD
  - source: 145
    name: WOOD
  - source: 150
    name: TRAP
  - source: 157
    name: IPCS
  - source: 161
    name: NBCN
  - source: 200
    name: ACFP
  - source: 201
    name: ALTU
  - source: 202
    name: EDJO
  - source: 203
    name: ASSC
  - source: 204
    name: FOAF
  - source: 208
    name: KING
  - source: 209
    name: AQUI
  - source: 210
    name: POLA
  - source: 217
    name: KINC
  - source: 218
    name: EMER
  - source: 222
    name: JPMS
  - source: 230
    name: TWCS
  - source: 231
    name: BIEB
  - source: 233
    name: JORY
  - source: 234
    name: WWCI
  - source: 235
    name: ACAD
  - source: 250
    name: INFI
  - source: 253
    name: IFOR
...
