---
service_locator:
  address: $service_locator_address
  username: market_data_feed
  password: $admin_password

feeds: 1
bbo_period: 1s
time_and_sales_period: 1s
sampling: 100ms
symbols: [A.TSX, B.TSX, C.TSX]
...
