---
service_locator:
  address: $service_locator_address
  username: $username
  password: $admin_password

enable_logging: false
use_broker_number: false
mpid: OMGA
consolidate_mpids: true
market: OMGA
sampling: 100ms
enable_retransmission: false
max_retransmissions: 10000
retransmission_block_size: 20000
host: 233.102.209.226:60004
interface: $local_interface:60004
retransmission_request_address: 142.201.149.44:60022
retransmission_response_address: 142.201.149.44:60054
...
